// Automatically generated by scripts/generate-build-info.cjs
// DO NOT EDIT MANUALLY - This file is automatically synchronized on build and live deployment.

export interface UpdateItem {
  title: string;
  description: string;
  icon?: string;
  tag?: string;
}

export interface SpecificationItem {
  label: string;
  value: string;
  detail: string;
  badge?: string;
}

export interface VersionHistoryItem {
  version: string;
  build: string;
  date: string;
  time: string;
  title: string;
  changes: string[];
}

export interface VersionInfo {
  version: string;
  buildNumber: string;
  commitHash: string;
  buildTimestamp: string;
  environment: string;
  lastUpdatedDate: string;
  lastUpdatedTime: string;
  releaseTitle: string;
  badge: string;
  channel: string;
  specifications: SpecificationItem[];
  whatsNew: UpdateItem[];
  versionHistory: VersionHistoryItem[];
}

export const APP_VERSION_INFO: VersionInfo = {
  "version": "v2.7.0",
  "buildNumber": "2026.10.04.1-42706153",
  "commitHash": "42706153",
  "buildTimestamp": "2026-10-04T18:36:39.934Z",
  "lastUpdatedDate": "October 5, 2026",
  "lastUpdatedTime": "12:06 AM IST",
  "releaseTitle": "Automated Semantic Versioning & Live Synchronization Engine",
  "badge": "Latest Live 🚀",
  "channel": "Production Release",
  "environment": "Cloud Production (Live)",
  "whatsNew": [
    {
      "title": "Automated Semantic Versioning (ऑटो-वर्ज़न सिस्टम)",
      "description": "कोड में नए बदलाव इंटरनेट पर डिप्लॉय होते ही सिस्टम स्वतः वर्ज़न को इंक्रीमेंट करता है। मैन्युअल नंबरिंग की ज़रूरत खत्म।",
      "icon": "🚀",
      "tag": "Auto-Build"
    },
    {
      "title": "Standardized Update Button (Check for Updates)",
      "description": "कन्फ्यूजिंग 'Re-Check Server' को हटाकर स्टैंडर्ड 'Check for Updates' बटन लगाया गया है।",
      "icon": "🔄",
      "tag": "UX"
    },
    {
      "title": "Clean Minimal Screen (क्लीन मेन स्क्रीन)",
      "description": "मेन स्क्रीन बिना किसी अनावश्‍यक वर्ज़न बैज के पूरी तरह क्लीन और डिस्ट्रैक्शन-फ्री है।",
      "icon": "✨",
      "tag": "Design"
    },
    {
      "title": "Instant Live Sync & Reload (तत्काल अपडेट लागू)",
      "description": "सर्वर पर नया वर्ज़न मिलते ही 'Reload & Apply' से ऐप तुरंत नए कोड के साथ ताज़ा हो जाता है।",
      "icon": "⚡",
      "tag": "Sync"
    }
  ],
  "specifications": [
    {
      "label": "AI Model & Engine",
      "value": "Gemini Live Multimodal API",
      "detail": "Ultra-fast bidirectional streaming via WebSocket (RFC 6455)",
      "badge": "Realtime"
    },
    {
      "label": "Audio Streaming Architecture",
      "value": "16-bit Linear PCM AudioWorklet",
      "detail": "16,000 Hz input sampling, 24,000 Hz high-fidelity Float32 output",
      "badge": "Full-Duplex"
    },
    {
      "label": "Latency & Response Budget",
      "value": "Zero-Lag (Budget = 0)",
      "detail": "Thinking delay completely bypassed for instantaneous natural conversation",
      "badge": "Instant"
    },
    {
      "label": "Voice Persona Lock",
      "value": "100% Locked Female Voice",
      "detail": "Strict female timbre lock on Kore (मोहिनी), Aoede (सुरीली) and Leda",
      "badge": "Sweet Tone"
    },
    {
      "label": "Background Media Sync",
      "value": "Session-Bound Lifecycle",
      "detail": "Video runs strictly while assistant is active; pauses & resets on idle",
      "badge": "Smart Sync"
    },
    {
      "label": "Turn-Taking & Interruption",
      "value": "250ms Fast VAD Engine",
      "detail": "Adaptive Voice Activity Detection with natural conversational barge-in",
      "badge": "Adaptive"
    }
  ],
  "versionHistory": [
    {
      "version": "v2.7.0",
      "build": "2026.10.04.1-42706153",
      "date": "October 5, 2026",
      "time": "12:06 AM IST",
      "title": "Automated Semantic Versioning & Live Synchronization Engine",
      "changes": [
        "Engineered automated semantic version bumper on code change",
        "Standardized UI button strictly to 'Check for Updates'",
        "Integrated deterministic content-hash build pipeline",
        "Fixed hash cyclic dependency for stable releases"
      ]
    },
    {
      "version": "v2.6.0",
      "build": "2026.10.04.2-prod",
      "date": "October 4, 2026",
      "time": "10:50 PM IST",
      "title": "Dedicated System Specification Section & Decoupled Personalization",
      "changes": [
        "Removed version details from Personalised Settings modal",
        "Created dedicated Specification & Version modal",
        "Added Comprehensive Technical System Specifications overview"
      ]
    },
    {
      "version": "v2.5.0",
      "build": "2026.10.04.1-prod",
      "date": "October 4, 2026",
      "time": "09:25 PM IST",
      "title": "Smart Video Sync & Lightning Conversational Flow",
      "changes": [
        "Smart Background video playback synchronized strictly to assistant active session",
        "Thinking delay bypassed (thinkingBudget: 0) for zero-wait speech output",
        "Continuous 16-bit PCM Audio Chunk alignment to eliminate sound distortion"
      ]
    },
    {
      "version": "v2.4.0",
      "build": "2026.09.29.3-prod",
      "date": "September 29, 2026",
      "time": "07:15 PM IST",
      "title": "Female Voice Safeguard & Activity Detection Tuning",
      "changes": [
        "Voice sanitization and persona enforcement",
        "Activity Handling tuning with 250ms VAD trigger"
      ]
    },
    {
      "version": "v2.0.0",
      "build": "2026.09.20.1-prod",
      "date": "September 20, 2026",
      "time": "03:40 PM IST",
      "title": "Gemini Live API Bidirectional Audio & Custom Video Backgrounds",
      "changes": [
        "Integration of Gemini 3.8 Live API WebSocket",
        "Custom video wallpaper upload and loop canvas"
      ]
    }
  ]
};
